# Generated by Django 4.0.4 on 2022-05-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamNo',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='player1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='player2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='player3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='player4',
            field=models.CharField(max_length=50),
        ),
    ]
